### ISSUE TITLE
期望项目加描述

### ISSUE THREAD

**Issue by lindexi** [dotnet-cn/awesome-dotnet-cn#1]

**Comment by tonyqus** [comment]
会加的，一步一步来，感谢关注

**Comment by lindexi** [comment]
@tonyqus  我这个项目不知是否适合加入 https://github.com/dotnet-campus/AsyncWorkerCollection/

**Comment by tonyqus** [comment]
你这项目是刚开始吗？nuget下载量有点少，不知道这个项目是干嘛用的，能介绍一下吗？
另外你是学生吗？我看到你们的组织叫dotnet-campus

**Comment by monksoul** [comment]
Fur 是 .NET 5 平台下极易入门、极速开发的 Web 应用框架。

Gitee：https://gitee.com/monksoul/Fur
GitHub：https://github.com/monksoul/Fur

不知是否可以收录？

**Comment by tonyqus** [comment]
@MonkSoul 项目不错，已收入。提几个小建议

1. 微软技术追新有风险，.NET 5的稳定性暂时无法确认，并不会有很多公司跟紧。你也是12年的资深码农，你应该明白我在说什么

2. 通用快速开发框架太多了，据我多年观察，实际项目生命周期也就2年的样子，这还是比较好的情况，比较差的情况几个月就挂了。建议挑某个特定行业进行技术攻坚，打通行业客户，技术框架才能存活。不要去抄Abp的模式，他的模式在国内恐怕行不通。

**Comment by tonyqus** [comment]
@lindexi 项目描述加了，这问题我关了。

**Comment by monksoul** [comment]
> @MonkSoul 项目不错，已收入。提几个小建议
> 
> 1. 微软技术追新有风险，.NET 5的稳定性暂时无法确认，并不会有很多公司跟紧。你也是12年的资深码农，你应该明白我在说什么
> 2. 通用快速开发框架太多了，据我多年观察，实际项目生命周期也就2年的样子，这还是比较好的情况，比较差的情况几个月就挂了。建议挑某个特定行业进行技术攻坚，打通行业客户，技术框架才能存活。不要去抄Abp的模式，他的模式在国内恐怕行不通。

明白，感谢这么详细的建议。感谢。

**Comment by monksoul** [comment]
咋又把我remove了?https://github.com/dotnet-cn/awesome-dotnet-cn/commit/a2be2ab45df7bf9ef6c71b3328737e38c9561580
