### ISSUE TITLE
SourceYard 制作 NuGet 源代码包的工具

### ISSUE THREAD

**Issue by lindexi** [dotnet-cn/awesome-dotnet-cn#3]
用于制作 NuGet 源代码包的工具，原本 NuGet 里面大部分都是 dll 引用。而这个工具提供了打包源代码作为引用。https://github.com/dotnet-campus/SourceYard

**Comment by askguanyu** [comment]
looks good

**Comment by tonyqus** [comment]
我看了下描述，这库是 把源代码打包进 Nuget 包的库？但我没想明白什么情况下需要这么干？能说一下吗？

**Comment by tonyqus** [comment]
由于长时间没有得到作者回复，此贴关闭
